import {TAXONOMY,LABELS,SEED_ITEMS} from './data.js';
import {getAllItems,putItem,deleteItem,bulkPutItems,getMeta,setMeta,clearItems} from './db.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const main=$('#mainContent'),title=$('#pageTitle'),itemDialog=$('#itemDialog'),installDialog=$('#installDialog'),toast=$('#toast');
const state={route:'closet',items:[],query:'',category:'All',installPrompt:null};
const emoji={Shirt:'👚',Pant:'👖',Skirt:'👗',Dress:'👗',Combo:'🧥',Coat:'🧥',Bag:'👜',Shoes:'👠',Accessorie:'💍',Belt:'➰',Swimware:'👙','Eye Lens':'◉',Socks:'🧦',Jumpsuit:'🩱'};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const label=(type,v)=>LABELS[type]?.[v]||v;
function say(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(say.t);say.t=setTimeout(()=>toast.classList.remove('show'),2200);}
function standalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;}
async function seed(){if(!(await getMeta('seeded-v1'))){await bulkPutItems(SEED_ITEMS);await setMeta('seeded-v1',true);}}
async function refresh(){state.items=(await getAllItems()).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));}
function setRoute(route){state.route=route;$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.route===route));render();}
function filtered(favs=false){const q=state.query.trim().toLowerCase();return state.items.filter(i=>(!favs||i.favorite)&&(state.category==='All'||i.category===state.category)&&(!q||[i.name,i.category,...(i.colors||[]),...(i.styles||[])].join(' ').toLowerCase().includes(q)));}
function card(i){const media=i.photo?`<img src="${i.photo}" alt="${esc(i.name)}" loading="lazy">`:`<div class="placeholder-art"><span>${emoji[i.category]||'◇'}</span><small>${esc(label('category',i.category))}</small></div>`;return `<article class="item-card" data-open="${esc(i.id)}" tabindex="0"><div class="item-media">${media}<button class="heart-button ${i.favorite?'is-favorite':''}" data-fav="${esc(i.id)}">${i.favorite?'♥':'♡'}</button></div><div class="item-info"><h3>${esc(i.name)}</h3><p>${esc(label('category',i.category))}</p><div class="chips">${(i.colors||[]).slice(0,2).map(c=>`<span>${esc(label('color',c))}</span>`).join('')}</div></div></article>`;}
function closet(favs=false){title.textContent=favs?'Yêu thích':'Tủ đồ của tôi';const list=filtered(favs);return `<section class="hero-card"><div><p class="hero-kicker">${favs?'NHỮNG MÓN TRÂN THÍCH':'MY CLOSET'}</p><h2>${favs?`${list.length} món yêu thích`:`${state.items.length} món trong tủ`}</h2><p>${favs?'Những món đánh dấu để tìm lại thật nhanh.':'Chọn nhanh, lọc theo loại và luôn mang tủ đồ theo bên mình.'}</p></div><div class="hero-orb">${favs?'♥':'✦'}</div></section>${favs?'':`<div class="search-wrap"><input id="searchInput" type="search" value="${esc(state.query)}" placeholder="Tìm túi, váy, màu sắc…"></div><div class="filter-row">${['All',...TAXONOMY.categories].map(c=>`<button class="filter-chip ${state.category===c?'active':''}" data-cat="${esc(c)}">${c==='All'?'Tất cả':esc(label('category',c))}</button>`).join('')}</div>`}<div class="section-heading"><h2>${favs?'Danh sách':'Bộ sưu tập'}</h2><span>${list.length}</span></div><section class="item-grid">${list.length?list.map(card).join(''):`<div class="empty-state"><strong>Chưa có gì ở đây</strong><p>Thêm một món mới để bắt đầu.</p></div>`}</section>`;}
function addView(){title.textContent='Thêm món mới';return `<section class="form-card"><div class="photo-picker" id="photoPreview"><div><span>＋</span><strong>Thêm ảnh</strong><small>Chụp hoặc chọn từ thư viện</small></div></div><form id="itemForm" class="item-form"><label>Tên món đồ<input name="name" required maxlength="80" placeholder="Ví dụ: Túi Melody"></label><label>Loại<select name="category">${TAXONOMY.categories.map(v=>`<option value="${v}">${esc(label('category',v))}</option>`).join('')}</select></label><fieldset><legend>Màu sắc</legend><div class="choice-grid">${TAXONOMY.colors.map(v=>`<label class="choice"><input type="checkbox" name="colors" value="${v}"><span>${esc(label('color',v))}</span></label>`).join('')}</div></fieldset><fieldset><legend>Phong cách</legend><div class="choice-grid">${TAXONOMY.styles.map(v=>`<label class="choice"><input type="checkbox" name="styles" value="${v}"><span>${esc(label('style',v))}</span></label>`).join('')}</div></fieldset><input id="photoInput" type="file" accept="image/*" capture="environment" hidden><button class="primary-button" type="submit">Lưu vào tủ đồ</button></form></section>`;}
function outfits(){title.textContent='Phối đồ';return `<section class="coming-card"><div class="coming-icon">◇</div><h2>Outfits đang tới</h2><p>Ở bước tiếp theo, Trân sẽ có thể ghép nhiều món thành một outfit, lưu theo dịp và nhận gợi ý tự động.</p><div class="mini-roadmap"><span>1. Chọn món</span><span>2. Tạo outfit</span><span>3. Gợi ý bằng AI</span></div></section>`;}
function profile(){title.textContent='Hồ sơ';return `<section class="profile-card"><div class="avatar">T</div><h2>Trân</h2><p>Tủ đồ cá nhân • ${state.items.length} món</p></section><section class="settings-list"><button id="profileInstall"><span>⌄</span><div><strong>Cài trên iPhone</strong><small>${standalone()?'Ứng dụng đã được cài':'Thêm vào màn hình chính'}</small></div><b>›</b></button><button id="exportBackup"><span>⇩</span><div><strong>Sao lưu dữ liệu</strong><small>Xuất JSON cục bộ</small></div><b>›</b></button><button id="importBackup"><span>⇧</span><div><strong>Khôi phục dữ liệu</strong><small>Nhập file JSON</small></div><b>›</b></button><button id="resetDemo" class="danger-row"><span>↺</span><div><strong>Khôi phục mẫu</strong><small>Xóa local và nạp seed</small></div><b>›</b></button><input id="backupInput" type="file" accept="application/json" hidden></section><p class="privacy-note">Dữ liệu V0.1 nằm trên thiết bị. Không có token Airtable trong ứng dụng.</p>`;}
function render(){main.innerHTML=state.route==='closet'?closet():state.route==='favorites'?closet(true):state.route==='add'?addView():state.route==='outfits'?outfits():profile();bind();}
function bind(){$('#searchInput')?.addEventListener('input',e=>{state.query=e.target.value;render();});$$('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;render();});$$('[data-open]').forEach(c=>{c.onclick=e=>{if(!e.target.closest('[data-fav]'))openItem(c.dataset.open);};c.onkeydown=e=>{if(e.key==='Enter')openItem(c.dataset.open);};});$$('[data-fav]').forEach(b=>b.onclick=async e=>{e.stopPropagation();const i=state.items.find(x=>x.id===b.dataset.fav);if(i){await putItem({...i,favorite:!i.favorite,updatedAt:new Date().toISOString()});await refresh();render();}});const pp=$('#photoPreview'),pi=$('#photoInput');if(pp&&pi){pp.onclick=()=>pi.click();pi.onchange=async()=>{const f=pi.files?.[0];if(!f)return;pi.dataset.photo=await compress(f);pp.innerHTML=`<img src="${pi.dataset.photo}" alt="Aperçu">`;};}$('#itemForm')?.addEventListener('submit',saveItem);$('#profileInstall')?.addEventListener('click',installHelp);$('#exportBackup')?.addEventListener('click',exportBackup);$('#importBackup')?.addEventListener('click',()=>$('#backupInput')?.click());$('#backupInput')?.addEventListener('change',importBackup);$('#resetDemo')?.addEventListener('click',resetDemo);}
async function saveItem(e){e.preventDefault();const f=new FormData(e.currentTarget),now=new Date().toISOString();await putItem({id:crypto.randomUUID(),airtableRecordId:null,name:String(f.get('name')||'').trim(),category:String(f.get('category')||'Accessorie'),colors:f.getAll('colors'),styles:f.getAll('styles'),photo:$('#photoInput')?.dataset.photo||null,favorite:false,createdAt:now,updatedAt:now});await refresh();say('Đã thêm vào tủ đồ ✦');setRoute('closet');}
async function compress(file){const img=new Image(),url=URL.createObjectURL(file);await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=url;});const max=1600,s=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);return c.toDataURL('image/jpeg',.82);}
function openItem(id){const i=state.items.find(x=>x.id===id);if(!i)return;itemDialog.innerHTML=`<div class="sheet-content"><button class="sheet-close" data-close>×</button>${i.photo?`<img class="detail-photo" src="${i.photo}" alt="${esc(i.name)}">`:`<div class="detail-placeholder">${emoji[i.category]||'◇'}</div>`}<div class="detail-body"><p class="eyebrow">${esc(label('category',i.category))}</p><h2>${esc(i.name)}</h2><div class="detail-chips">${[...(i.colors||[]).map(v=>label('color',v)),...(i.styles||[]).map(v=>label('style',v))].map(v=>`<span>${esc(v)}</span>`).join('')}</div><div class="detail-actions"><button id="detailFav" class="secondary-button">${i.favorite?'♥ Bỏ yêu thích':'♡ Yêu thích'}</button><button id="detailDelete" class="danger-button">Xóa</button></div></div></div>`;itemDialog.showModal();itemDialog.querySelector('[data-close]').onclick=()=>itemDialog.close();itemDialog.querySelector('#detailFav').onclick=async()=>{await putItem({...i,favorite:!i.favorite,updatedAt:new Date().toISOString()});itemDialog.close();await refresh();render();};itemDialog.querySelector('#detailDelete').onclick=async()=>{if(!confirm(`Xóa “${i.name}” khỏi tủ đồ?`))return;await deleteItem(i.id);itemDialog.close();await refresh();say('Đã xóa');render();};}
function installHelp(){if(standalone())return say('Ứng dụng đã được cài ✓');if(state.installPrompt)return state.installPrompt.prompt();const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);installDialog.innerHTML=`<div class="sheet-content install-sheet"><button class="sheet-close" data-close>×</button><div class="coming-icon">⌄</div><h2>${ios?'Cài trên iPhone':'Cài ứng dụng'}</h2>${ios?'<ol><li>Mở bằng <strong>Safari</strong>.</li><li>Chạm <strong>Chia sẻ</strong>.</li><li>Chọn <strong>Thêm vào Màn hình chính</strong>.</li><li>Chạm <strong>Thêm</strong>.</li></ol>':'<p>Mở menu trình duyệt và chọn <strong>Cài ứng dụng</strong>.</p>'}</div>`;installDialog.showModal();installDialog.querySelector('[data-close]').onclick=()=>installDialog.close();}
function exportBackup(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),items:state.items},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`tran-closet-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);}
async function importBackup(e){const f=e.target.files?.[0];if(!f)return;try{const p=JSON.parse(await f.text());if(!Array.isArray(p.items))throw 0;await clearItems();await bulkPutItems(p.items);await refresh();say('Đã khôi phục dữ liệu ✓');render();}catch{say('File sao lưu không hợp lệ');}}
async function resetDemo(){if(!confirm('Khôi phục dữ liệu mẫu? Dữ liệu cục bộ hiện tại sẽ bị xóa.'))return;await clearItems();await bulkPutItems(SEED_ITEMS);await refresh();say('Đã khôi phục dữ liệu mẫu');render();}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;});window.addEventListener('appinstalled',()=>{state.installPrompt=null;say('Đã cài Trân Closet ✓');});$('#installButton').onclick=installHelp;$$('.nav-item').forEach(n=>n.onclick=()=>setRoute(n.dataset.route));if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));await seed();await refresh();render();
