import {TAXONOMY,LABELS,SEED_ITEMS} from './data.js';
import {getAllItems,putItem,deleteItem,bulkPutItems,getMeta,setMeta,clearItems,clearMutations} from './db.js';
import {queueMutation,flushMutationQueue,pendingMutationCount,getSyncConfig,saveSyncConfig,testSyncConnection} from './sync-client.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const main=$('#mainContent'),title=$('#pageTitle'),itemDialog=$('#itemDialog'),installDialog=$('#installDialog'),toast=$('#toast');
const state={route:'closet',items:[],query:'',category:'All',installPrompt:null,pending:0,syncConfigured:false,syncing:false};
const emoji={Shirt:'👚',Pant:'👖',Skirt:'👗',Dress:'👗',Combo:'🧥',Coat:'🧥',Bag:'👜',Shoes:'👠',Accessorie:'💍',Belt:'➰',Swimware:'👙','Eye Lens':'◉',Socks:'🧦',Jumpsuit:'🩱'};
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const label=(type,v)=>LABELS[type]?.[v]||v;
function say(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(say.t);say.t=setTimeout(()=>toast.classList.remove('show'),2400);}
function standalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;}
async function seed(){if(!(await getMeta('seeded-v1'))){await bulkPutItems(SEED_ITEMS);await setMeta('seeded-v1',true);}}
async function refresh(){state.items=(await getAllItems()).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));state.pending=await pendingMutationCount();const cfg=await getSyncConfig();state.syncConfigured=Boolean(cfg.endpoint&&cfg.token);}
function setRoute(route){state.route=route;$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.route===route));render();}
function filtered(favs=false){const q=state.query.trim().toLowerCase();return state.items.filter(i=>(!favs||i.favorite)&&(state.category==='All'||i.category===state.category)&&(!q||[i.name,i.category,...(i.colors||[]),...(i.styles||[])].join(' ').toLowerCase().includes(q)));}
function syncText(i){if(i.syncState==='pending-create')return 'Chờ tạo';if(i.syncState==='pending-update')return 'Chờ cập nhật';if(i.syncState==='pending-photo')return 'Chờ ảnh';if(i.syncState==='awaiting-snapshot')return 'Đã gửi';return '';}
function card(i){const media=i.photo?`<img src="${i.photo}" alt="${esc(i.name)}" loading="lazy">`:`<div class="placeholder-art"><span>${emoji[i.category]||'◇'}</span><small>${esc(label('category',i.category))}</small></div>`;const sync=syncText(i);return `<article class="item-card" data-open="${esc(i.id)}" tabindex="0"><div class="item-media">${media}<button class="heart-button ${i.favorite?'is-favorite':''}" data-fav="${esc(i.id)}">${i.favorite?'♥':'♡'}</button></div><div class="item-info"><h3>${esc(i.name)}</h3><p>${esc(label('category',i.category))}${sync?` · <span class="sync-mini">${esc(sync)}</span>`:''}</p><div class="chips">${(i.colors||[]).slice(0,2).map(c=>`<span>${esc(label('color',c))}</span>`).join('')}</div></div></article>`;}
function closet(favs=false){title.textContent=favs?'Yêu thích':'Tủ đồ của tôi';const list=filtered(favs);return `<section class="hero-card"><div><p class="hero-kicker">${favs?'NHỮNG MÓN TRÂN THÍCH':'TỦ ĐỒ CỦA TRÂN'}</p><h2>${favs?`${list.length} món yêu thích`:`${state.items.length} món trong tủ`}</h2><p>${favs?'Những món đánh dấu để tìm lại thật nhanh.':state.pending?`${state.pending} thay đổi đang chờ đồng bộ. Tủ đồ vẫn dùng được ngoại tuyến.`:'Chọn nhanh, lọc theo loại và luôn mang tủ đồ theo bên mình.'}</p></div><div class="hero-orb">${favs?'♥':state.pending?'↻':'✦'}</div></section>${favs?'':`<div class="search-wrap"><input id="searchInput" type="search" value="${esc(state.query)}" placeholder="Tìm túi, váy, màu sắc…"></div><div class="filter-row">${['All',...TAXONOMY.categories].map(c=>`<button class="filter-chip ${state.category===c?'active':''}" data-cat="${esc(c)}">${c==='All'?'Tất cả':esc(label('category',c))}</button>`).join('')}</div>`}<div class="section-heading"><h2>${favs?'Danh sách':'Bộ sưu tập'}</h2><span>${list.length}</span></div><section class="item-grid">${list.length?list.map(card).join(''):`<div class="empty-state"><strong>Chưa có gì ở đây</strong><p>Thêm một món mới để bắt đầu.</p></div>`}</section>`;}
function itemFields(i={}){return `<label>Tên món đồ<input name="name" required maxlength="80" value="${esc(i.name||'')}" placeholder="Ví dụ: Túi Melody"></label><label>Loại<select name="category">${TAXONOMY.categories.map(v=>`<option value="${v}" ${i.category===v?'selected':''}>${esc(label('category',v))}</option>`).join('')}</select></label><fieldset><legend>Màu sắc</legend><div class="choice-grid">${TAXONOMY.colors.map(v=>`<label class="choice"><input type="checkbox" name="colors" value="${v}" ${(i.colors||[]).includes(v)?'checked':''}><span>${esc(label('color',v))}</span></label>`).join('')}</div></fieldset><fieldset><legend>Phong cách</legend><div class="choice-grid">${TAXONOMY.styles.map(v=>`<label class="choice"><input type="checkbox" name="styles" value="${v}" ${(i.styles||[]).includes(v)?'checked':''}><span>${esc(label('style',v))}</span></label>`).join('')}</div></fieldset>`;}
function addView(){title.textContent='Thêm món mới';return `<section class="form-card"><div class="photo-picker" id="photoPreview"><div><span>＋</span><strong>Thêm ảnh</strong><small>Chụp hoặc chọn từ thư viện</small></div></div><form id="itemForm" class="item-form">${itemFields()}<input id="photoInput" type="file" accept="image/*" capture="environment" hidden><button class="primary-button" type="submit">Lưu vào tủ đồ</button></form></section>`;}
function outfits(){title.textContent='Phối đồ';return `<section class="coming-card"><div class="coming-icon">◇</div><h2>Outfits đang tới</h2><p>Ở bước tiếp theo, Trân sẽ có thể ghép nhiều món thành một outfit, lưu theo dịp và nhận gợi ý tự động.</p><div class="mini-roadmap"><span>1. Chọn món</span><span>2. Tạo outfit</span><span>3. Gợi ý bằng AI</span></div></section>`;}
function profile(){title.textContent='Hồ sơ';return `<section class="profile-card"><div class="avatar">T</div><h2>Trân</h2><p>Tủ đồ cá nhân • ${state.items.length} món</p></section><section class="sync-card"><div class="sync-head"><div><p class="eyebrow">AIRTABLE</p><h2>${state.syncConfigured?'Đồng bộ đã cấu hình':'Kết nối đồng bộ'}</h2></div><span class="sync-dot ${state.syncConfigured?'online':''}"></span></div><p class="sync-copy">${state.pending?`${state.pending} thay đổi đang chờ gửi.`:'Không có thay đổi đang chờ.'}</p><form id="syncConfigForm" class="sync-form"><label>Địa chỉ Worker<input name="endpoint" type="url" placeholder="https://tran-closet-sync…workers.dev"></label><label>Khóa đồng bộ<input name="token" type="password" autocomplete="off" placeholder="Khóa riêng của Trân"></label><div class="sync-actions"><button class="secondary-button" type="button" id="testSync">Kiểm tra</button><button class="primary-button" type="submit">Lưu kết nối</button></div></form><button class="secondary-button sync-now" id="syncNow" ${state.syncing?'disabled':''}>${state.syncing?'Đang đồng bộ…':`Đồng bộ ngay${state.pending?` (${state.pending})`:''}`}</button></section><section class="settings-list"><button id="profileInstall"><span>⌄</span><div><strong>Cài trên iPhone</strong><small>${standalone()?'Ứng dụng đã được cài':'Thêm vào màn hình chính'}</small></div><b>›</b></button><button id="exportBackup"><span>⇩</span><div><strong>Sao lưu dữ liệu</strong><small>Xuất JSON cục bộ</small></div><b>›</b></button><button id="importBackup"><span>⇧</span><div><strong>Khôi phục dữ liệu</strong><small>Nhập file JSON</small></div><b>›</b></button><button id="resetDemo" class="danger-row"><span>↺</span><div><strong>Tải lại dữ liệu cục bộ</strong><small>Xóa dữ liệu local và nạp lại snapshot</small></div><b>›</b></button><input id="backupInput" type="file" accept="application/json" hidden></section><p class="privacy-note">Khóa Airtable không nằm trong PWA. Ứng dụng chỉ lưu khóa đồng bộ riêng của thiết bị và envoie les mutations au Worker sécurisé.</p>`;}
function render(){main.innerHTML=state.route==='closet'?closet():state.route==='favorites'?closet(true):state.route==='add'?addView():state.route==='outfits'?outfits():profile();bind();}
async function bindSyncForm(){const form=$('#syncConfigForm');if(!form)return;const cfg=await getSyncConfig();form.elements.endpoint.value=cfg.endpoint||'';form.elements.token.value=cfg.token||'';form.onsubmit=async e=>{e.preventDefault();await saveSyncConfig(form.elements.endpoint.value,form.elements.token.value);await refresh();say('Đã lưu kết nối đồng bộ');render();};$('#testSync')?.addEventListener('click',async()=>{await saveSyncConfig(form.elements.endpoint.value,form.elements.token.value);const result=await testSyncConnection();say(result.ok?'Kết nối Worker thành công ✓':result.status===401?'Khóa đồng bộ không đúng':'Không kết nối được Worker');await refresh();render();});$('#syncNow')?.addEventListener('click',()=>syncNow(false));}
function bind(){$('#searchInput')?.addEventListener('input',e=>{state.query=e.target.value;render();});$$('[data-cat]').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;render();});$$('[data-open]').forEach(c=>{c.onclick=e=>{if(!e.target.closest('[data-fav]'))openItem(c.dataset.open);};c.onkeydown=e=>{if(e.key==='Enter')openItem(c.dataset.open);};});$$('[data-fav]').forEach(b=>b.onclick=async e=>{e.stopPropagation();const i=state.items.find(x=>x.id===b.dataset.fav);if(i){await putItem({...i,favorite:!i.favorite});await refresh();render();}});const pp=$('#photoPreview'),pi=$('#photoInput');if(pp&&pi){pp.onclick=()=>pi.click();pi.onchange=async()=>{const f=pi.files?.[0];if(!f)return;pi.dataset.photo=await compress(f);pp.innerHTML=`<img src="${pi.dataset.photo}" alt="Aperçu">`;};}$('#itemForm')?.addEventListener('submit',saveItem);$('#profileInstall')?.addEventListener('click',installHelp);$('#exportBackup')?.addEventListener('click',exportBackup);$('#importBackup')?.addEventListener('click',()=>$('#backupInput')?.click());$('#backupInput')?.addEventListener('change',importBackup);$('#resetDemo')?.addEventListener('click',resetLocal);bindSyncForm();}
async function saveItem(e){e.preventDefault();const f=new FormData(e.currentTarget),now=new Date().toISOString();const item={id:crypto.randomUUID(),airtableRecordId:null,name:String(f.get('name')||'').trim(),category:String(f.get('category')||'Accessorie'),colors:f.getAll('colors'),styles:f.getAll('styles'),photo:$('#photoInput')?.dataset.photo||null,favorite:false,source:'local',syncState:'pending-create',createdAt:now,updatedAt:now,cloudWriteAt:null};await putItem(item);await queueMutation('create',item);await refresh();say('Đã thêm vào tủ đồ ✦');setRoute('closet');syncNow(true);}
async function compress(file){const img=new Image(),url=URL.createObjectURL(file);await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=url;});const max=1500,s=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*s);c.height=Math.round(img.height*s);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);return c.toDataURL('image/jpeg',.78);}
function openItem(id){const i=state.items.find(x=>x.id===id);if(!i)return;itemDialog.innerHTML=`<div class="sheet-content"><button class="sheet-close" data-close>×</button>${i.photo?`<img class="detail-photo" src="${i.photo}" alt="${esc(i.name)}">`:`<div class="detail-placeholder">${emoji[i.category]||'◇'}</div>`}<div class="detail-body"><p class="eyebrow">${esc(label('category',i.category))}</p><h2>${esc(i.name)}</h2><div class="detail-chips">${[...(i.colors||[]).map(v=>label('color',v)),...(i.styles||[]).map(v=>label('style',v))].map(v=>`<span>${esc(v)}</span>`).join('')}</div>${syncText(i)?`<p class="sync-detail">↻ ${esc(syncText(i))}</p>`:''}<div class="detail-actions three"><button id="detailFav" class="secondary-button">${i.favorite?'♥':'♡'}</button><button id="detailEdit" class="secondary-button">Sửa</button><button id="detailDelete" class="danger-button">Xóa</button></div></div></div>`;itemDialog.showModal();itemDialog.querySelector('[data-close]').onclick=()=>itemDialog.close();itemDialog.querySelector('#detailFav').onclick=async()=>{await putItem({...i,favorite:!i.favorite});itemDialog.close();await refresh();render();};itemDialog.querySelector('#detailEdit').onclick=()=>openEdit(i.id);itemDialog.querySelector('#detailDelete').onclick=async()=>{if(!confirm(`Xóa “${i.name}” khỏi tủ đồ?`))return;await queueMutation('delete',i);await deleteItem(i.id);itemDialog.close();await refresh();say(navigator.onLine?'Đã xóa · đang đồng bộ':'Đã xóa · sẽ đồng bộ khi có mạng');render();syncNow(true);};}
function openEdit(id){const i=state.items.find(x=>x.id===id);if(!i)return;itemDialog.innerHTML=`<div class="sheet-content edit-sheet"><button class="sheet-close" data-close>×</button><div class="detail-body"><p class="eyebrow">CHỈNH SỬA</p><h2>${esc(i.name)}</h2>${i.photo?`<img class="edit-photo" src="${i.photo}" alt="${esc(i.name)}">`:''}<form id="editItemForm" class="item-form">${itemFields(i)}<p class="form-note">Thay ảnh sẽ được thêm trong bản cập nhật tiếp theo. Ảnh hiện tại được giữ nguyên.</p><button class="primary-button" type="submit">Lưu thay đổi</button></form></div></div>`;itemDialog.querySelector('[data-close]').onclick=()=>itemDialog.close();itemDialog.querySelector('#editItemForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),now=new Date().toISOString();const updated={...i,name:String(f.get('name')||'').trim(),category:String(f.get('category')||'Accessorie'),colors:f.getAll('colors'),styles:f.getAll('styles'),syncState:i.airtableRecordId?'pending-update':'pending-create',updatedAt:now};await putItem(updated);await queueMutation('update',updated);itemDialog.close();await refresh();say('Đã lưu thay đổi');render();syncNow(true);};}
async function syncNow(silent=true){if(state.syncing)return;state.syncing=true;if(!silent&&state.route==='profile')render();const result=await flushMutationQueue();await refresh();state.syncing=false;if(!silent){if(result.ok)say('Đồng bộ Airtable hoàn tất ✓');else if(result.offline)say('Ngoại tuyến · thay đổi vẫn được lưu');else if(result.configured===false)say('Hãy cấu hình Worker trước');else if(result.status===401)say('Khóa đồng bộ không đúng');else say(`${state.pending} thay đổi vẫn đang chờ`);}render();}
function installHelp(){if(standalone())return say('Ứng dụng đã được cài ✓');if(state.installPrompt)return state.installPrompt.prompt();const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);installDialog.innerHTML=`<div class="sheet-content install-sheet"><button class="sheet-close" data-close>×</button><div class="coming-icon">⌄</div><h2>${ios?'Cài trên iPhone':'Cài ứng dụng'}</h2>${ios?'<ol><li>Mở bằng <strong>Safari</strong>.</li><li>Chạm <strong>Chia sẻ</strong>.</li><li>Chọn <strong>Thêm vào Màn hình chính</strong>.</li><li>Chạm <strong>Thêm</strong>.</li></ol>':'<p>Mở menu trình duyệt và chọn <strong>Cài ứng dụng</strong>.</p>'}</div>`;installDialog.showModal();installDialog.querySelector('[data-close]').onclick=()=>installDialog.close();}
function exportBackup(){const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),items:state.items},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`tran-closet-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);}
async function importBackup(e){const f=e.target.files?.[0];if(!f)return;try{const p=JSON.parse(await f.text());if(!Array.isArray(p.items))throw 0;await clearItems();await clearMutations();await bulkPutItems(p.items);await refresh();say('Đã khôi phục dữ liệu ✓');render();}catch{say('File sao lưu không hợp lệ');}}
async function resetLocal(){if(!confirm('Xóa dữ liệu cục bộ trên thiết bị? Dữ liệu Airtable sẽ không bị xóa.'))return;await clearItems();await clearMutations();await setMeta('seeded-v1',false);await seed();await refresh();say('Đã tải lại dữ liệu cục bộ');render();}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;});window.addEventListener('appinstalled',()=>{state.installPrompt=null;say('Đã cài Trân Closet ✓');});window.addEventListener('online',()=>syncNow(true));$('#installButton').onclick=installHelp;$$('.nav-item').forEach(n=>n.onclick=()=>setRoute(n.dataset.route));if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));await seed();await refresh();render();setTimeout(()=>syncNow(true),700);
